=== Augure34/astro-products/.astro/collections/nettoyage.schema.json
{
  "$ref": "#/definitions/nettoyage",
  "definitions": {
    "nettoyage": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "price": {
          "type": "object",
          "properties": {
            "daily": {
              "type": "number"
            },
            "weekly": {
              "type": "number"
            }
          },
          "required": [
            "daily",
            "weekly"
          ],
          "additionalProperties": false
        },
        "image": {
          "type": "string",
          "format": "uri"
        },
        "manufacturer": {
          "type": "string"
        },
        "model": {
          "type": "string"
        },
        "batteryType": {
          "type": "string"
        },
        "tags": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "manual": {
          "type": "string",
          "format": "uri"
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "description",
        "price"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== Augure34/astro-products/products/metalworking/plasma-cutter.json
{
    "name": "Plasma Cutter",
    "description": "Corded circular saw for making precise cuts in wood and other materials.",
    "price": {
      "daily": 25.00,
      "weekly": 125.00
    },
    "image": "https://placehold.co/400x300/EEE/31343C?text=Plasma+Cutter&font=Montserrat",
    "manufacturer": "Makita",
    "model": "XSR01Z",
    "batteryType": "Lithium-Ion"
}
